# Generated by Django 4.2.19 on 2025-02-20 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='Фамилия автора')),
                ('first_name', models.CharField(help_text='Введите имя автора', max_length=100, verbose_name='Имя автора')),
                ('other_name', models.CharField(help_text='Введите отчество автора', max_length=100, verbose_name='Отчество автора')),
                ('image', models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='static/main/image/autor', verbose_name='Обложка')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите жанр', max_length=100, verbose_name='Жанр')),
                ('image', models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='static/main/image/genre', verbose_name='Обложка')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(help_text='Введите название', max_length=200, verbose_name='Название')),
                ('description', models.CharField(help_text='Введите описание', max_length=1000, verbose_name='Описание')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='static/main/image/book', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('views_count', models.IntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
                ('authors', models.ManyToManyField(related_name='books', to='main.autor', verbose_name='Авторы')),
                ('genre', models.ForeignKey(help_text='Выберите жанр', on_delete=django.db.models.deletion.CASCADE, to='main.genre', verbose_name='Жанр')),
            ],
        ),
    ]
