# Generated by Django 4.2.19 on 2025-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='.static/main/image/autor', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='Теги'),
        ),
    ]
