# Generated by Django 4.2.19 on 2025-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_alter_autor_image_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='static/main/image/autor', verbose_name='Обложка'),
        ),
    ]
