# Generated by Django 4.2.19 on 2025-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biography',
            field=models.TextField(blank=True, help_text='Введите текст', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='image/autor', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='image/book', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите обложку книги', null=True, upload_to='image/genre', verbose_name='Обложка'),
        ),
    ]
