# Generated by Django 4.2.19 on 2025-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_autor_biography_alter_autor_image_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biography',
            field=models.TextField(blank=True, help_text='Введите биографию', null=True, verbose_name='Биография'),
        ),
    ]
