# Generated by Django 4.2.19 on 2025-03-19 17:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Введите биографию', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Введите текст своего произведения', verbose_name='Текст'),
        ),
    ]
